### ISSUE TITLE
No module named ‘langchain’该怎么解决

### ISSUE THREAD

**Issue by P-RET** [CSHaitao/LexiLaw#10]
Traceback (most recent call last):
  File "F:\vs_repos\lewilex\demo\main.py", line 6, in <module>
    from clc.langchain_application import LangChainApplication
  File "F:\vs_repos\lewilex\demo\clc\langchain_application.py", line 12, in <module>
    from langchain.chains import RetrievalQA
ModuleNotFoundError: No module named 'langchain'

**Comment by CSHaitao** [comment]
可以安装一下
